backend_qemu: Avoid file ID collisions when multiple mounts share the same host path
go-debos/fakemachine pull request #105
Opened 2022-09-26 15:15 UTC by evelikov

Currently we get a useful warning like:

9p: Multiple devices detected in same VirtFS export, which might lead to file ID collisions and severe misbehaviours on guest!
You should either use a separate export for each device shared from host or use virtfs option 'multidevs=remap'!

So let's add the option to avoid the issue. Requires QEMU >= 4.2.0

[Emil Velikov]
 - Rebase, tweak commit message

2022-09-26 15:19 UTC, obbardc requested changes
With the commit message changed to `backend_qemu: ...`, look good to me!

2022-09-27 11:24 UTC, obbardc approved these changes

2022-09-28 12:53 UTC, obbardc requested changes
Commit message is a bit lacking;

```
backend_qemu: Avoid file ID collisions when multiple mounts share the same host path

When multiple mounts share the same host path, qemu warns that this situation may lead to ID collisions:

    9p: Multiple devices detected in same VirtFS export, which might lead to file
    ID collisions and severe misbehaviours on guest!
    You should either use a separate export for each device shared from host or
    use virtfs option 'multidevs=remap'!

Setting the multidevs=remap argument for the block device allows sharing more than one device per export by remapping inodes from host to guest appropriately. This change requires QEMU >= 4.2.0.
```

2022-10-31 10:31 UTC, evelikov commented
All done - sorry for the delay.

2022-10-31 10:32 UTC, obbardc commented
bors r+

2022-10-31 10:40 UTC, merged