cmd: Add 'version' option
go-debos/fakemachine pull request #220
Opened 2024-10-30 21:13 UTC by daissi

This 'version' option prints the fakemachine version. Fix #200

2024-10-30 21:21 UTC, obbardc approved these changes

2024-10-30 21:22 UTC, obbardc commented
CI fails because of https://github.com/go-debos/fakemachine/pull/218

2024-11-06 01:07 UTC, obbardc commented on cmd/fakemachine/main.go
> +const Version = "0.0.10"
Untested but pretty sure we can inject the version at build time with `go build -ldflags "-X main.Version=$VERSION"`.

How do you feel about
1) injecting the version in the GitHub action based on git commit
2) injecting the same version in the Debian packaging

I looked for existing libraries to do this, like in rust, but couldn't find anything.

(Also the same will be true for debos)

2024-11-06 21:00 UTC, sjoerdsimons commented on cmd/fakemachine/main.go
> +const Version = "0.0.10"
Is that what's typical in the go space (surely others do this as well)? But yeah in principle that sounds fine, my main concern is really that it's too easy to forget to update :)

2025-01-28 12:12 UTC, daissi commented on cmd/fakemachine/main.go
> +const Version = "0.0.10"
Now, the version is injected at build time based on `git describe --tags HEAD`. Is that better?

2025-02-16 08:48 UTC, sjoerdsimons commented on cmd/fakemachine/main.go
> +const Version = "0.0.10"
It's getting there; but it's incomplete.. I ended up doing a bit of a deep dive on go versioning yesterday...

Essentially we've got 3 different variations:
1. Build where the build system can set a version;
1. self-build fakemachine from a remote repo e.g. `go install github.com/go-debos/fakemachine/cmd/fakemachine@latest` . 
1. self-build fakemachine from a local git checkout e.g. `go build ./cmd/fakemachine` 

This patch is only covering the first case, by taking advantage of our CI pipeline setting the version. The Debian packaging case can be covered the same way. For example the [caddy packaging](https://salsa.debian.org/go-team/packages/caddy/-/blob/debian/sid/debian/rules?ref_type=heads#L13)  ends up doing that.

For the other two cases it seems best to use the golang [debug buildinfo](https://pkg.go.dev/runtime/debug#BuildInfo). When building from a remote info the `Main` field ends up with a reasonable version, while when building locally the `Settings` field contains [vcs information](https://pkg.go.dev/runtime/debug#BuildSetting). 

as a POC i played with https://github.com/sjoerdsimons/go-version-test/blob/main/cmd/go-version-test/main.go, which seems to what i'd expect in the various different cases (see last [actions run](https://github.com/sjoerdsimons/go-version-test/actions)). So we probably want someting similar here

2025-02-25 10:04 UTC, obbardc commented
I've added this to the [v0.0.9](https://github.com/go-debos/fakemachine/milestone/4) milestone, the changes look small enough to me to get that in the next week or so? :-)

2025-02-25 10:06 UTC, obbardc requested changes

2025-02-25 10:06 UTC, obbardc commented on cmd/fakemachine/main.go
> +var Version string = "none"
Does it make sense to expose this in the fakemachine go API (so we could e.g print the version of fakemachine used in debos debug) ? It could come later after this PR.

2025-02-25 10:06 UTC, obbardc commented on .github/workflows/ci.yml
> +      run: go build -o fakemachine -ldflags="-X main.Version=$(git describe --tags HEAD)" cmd/fakemachine/main.go
I'd rather build the version as a variable (which could be overwritten?) first in a separate step and output as variable.

2025-02-25 14:13 UTC, sjoerdsimons approved these changes

2025-02-25 14:13 UTC, sjoerdsimons requested changes
see long comment :)

2025-02-25 15:14 UTC, sjoerdsimons commented on cmd/fakemachine/main.go
> +var Version string = "none"
That's very hard with golang; remember is a static library. Fakemachine, the library, itself has no idea what version it is inherently. Debos could figure it our from the golang buildinfo, but that gets cleared when doing debian builds for some reason

2025-02-25 15:21 UTC, obbardc commented on cmd/fakemachine/main.go
> +var Version string = "none"
Sounds reasonable enough.

2025-03-03 08:15 UTC, sjoerdsimons commented
> I've added this to the [v0.0.9](https://github.com/go-debos/fakemachine/milestone/4) milestone, the changes look small enough to me to get that in the next week or so? :-)

well i already tagged 0.0.11 :)  As i noted in one of the threads ; golang versioning is full of subtleties, so i expect it to at least take some review rounds

2025-03-04 10:37 UTC, obbardc commented
> > I've added this to the [v0.0.9](https://github.com/go-debos/fakemachine/milestone/4) milestone, the changes look small enough to me to get that in the next week or so? :-)
> 
> well i already tagged 0.0.11 :) As i noted in one of the threads ; golang versioning is full of subtleties, so i expect it to at least take some review rounds

ok, I set the correct milestone now.

2025-04-01 13:16 UTC, daissi commented on .github/workflows/ci.yml
> +      run: go build -o fakemachine -ldflags="-X main.Version=$(git describe --tags HEAD)" cmd/fakemachine/main.go
This should be fixed now

2025-04-03 19:57 UTC, sjoerdsimons approved these changes
Changes look good to me; Sadly CI fails but it's not clear why (doesn't look like your changes could cause it but...)

2025-04-05 08:45 UTC, obbardc approved these changes

2025-04-05 09:03 UTC, merged